---
- hosts: all
  become: true
  remote_user: ansible
  gather_facts: false
  tasks:
  #copy the repo file from local server to remote server manged node
   - name: copy repo file to remote server.
     copy:
      src: /home/ansible/rhel82.repo
      dest: /etc/yum.repos.d/rhel82.repo
      mode: 0644
      owner: root
      group: root
  #install httpd package
   - name: install Apache Webserver
     yum:
      name: httpd
      #state:latest
      state: installed
  #copy index.html from local server to remote server.
   - name: copy the index file
     copy:
      src: /home/ansible/index.html
      dest: /var/www/html/index.html
      mode: 0644
      owner: root
      group: root

  # Add http service to ffirewalld and enabled it immediately
   - name: add http port to firewall
     firewalld:
      service: http
      state: enabled
      permanent: yes
      immediate: yes
  #start the httpd sevice
   - name: start httpd web servcie
     service:
      name: httpd
      state: started
      enabled: yes
...
#end of the play
