#Ansible playbook can have multiple plays. This playbook demostrates multiple
#plays in single playbook
...
- name: play1 -install samba
  hosts: 192.16.13.200
  remote_user: ansible
  become: true
  task:
   - name: task to install the samba server
     yum:
     name: samba
     state: latest
#Endof the firest play
#Beginning of the second play
 - name: play2 -  start samba services
  hosta: 192.168.13.200
  remote_user: ansible
  become: true
  tasks:
  - name: Task1 - start smbd
    service:
    name: smb
    state: started
    - name:Task2 - Start nmbd
    service:
     namne: nmb
     state: started
#End of the second play
...
#End of the playbook