---
- name: play to demonstrate lineinfile
  hosts: 192.168.22.200
  become: yes
  remote_user: ansible
  tasks:
  - name: task to edit a line before the given pattern matching text file
    lineinfile: 
     path: /etc/ssh/sshd_config
     insertbefore: ^PermitRootLogin
     line: "#the below line tells if root is allowed to login to any server.."
     backup: yes
     state: present
     #insertafter: "#the above line enabled if the root user can login to any system...!"
...