---
- name: play to replace permitRootLogin in /etc/ssh/sshd_config file
  hosts: 192.168.19.200
  become: true
  remote_user: ansible
  tasks:
  - name: Replace PermitRootLogin
    lineinfile:
     path: /etc/ssh/sshd_config
     regexp: ^PermitRootLogin
     line: "PermitRootLogin=no"
     backup: yes
  - name: Restart sshd
    service:
     name: sshd
     state: restarted
...
#End of the file